# 全局默认配置 (无 section 名)[citation:12]
anchor = top-right
edge-margin-vertical = 10
edge-margin-horizontal = 10
notification-margin = 10
padding-vertical = 14
padding-horizontal = 16
max-width = 400
background = 1a1a1ad9
border-color = 00000000
border-size = 0
border-radius = 8
default-timeout = 0
title-color = cdd6f4ff
body-color = cdd6f4ff

title-font = JetBrainsMono Nerd Font:weight=bold:size=11
summary-font = Noto Sans CJK SC:size=12
body-font = Noto Sans CJK SC=italic:size=10

min-width = 300
max-width = 500

