[main]
#font = MesloLGS Nerd Font Mono:size=10
font  = JetBrainsMono Nerd Font Mono:size=10, Noto Sans Mono CJK SC:size=10
title = xterm

[colors-dark]
alpha=0.8

foreground=e6e0e9
background=141218
selection-foreground=e6e0e9
selection-background=4f378b
cursor = 141218 d0bcff

# 暗色 (regular0-7)
regular0=4a4653      # 暗灰
regular1=ff728f      # 红
regular2=7fff9a      # 绿
regular3=ffda72      # 黄
regular4=9d8ad0      # 紫
regular5=8a6ab0      # 紫红
regular6=8ab8d0      # 蓝
regular7=cdd6f4      # 白

# 亮色 (bright0-7)
bright0=9d99a5       # 亮灰
bright1=ff9fb2       # 亮红
bright2=a5ffb8       # 亮绿
bright3=ffe7a5       # 亮黄
bright4=bba0f0       # 亮紫
bright5=d4a0e8       # 亮紫红
bright6=8ac0e8       # 亮蓝
bright7=f4efff       # 亮白

dim-blend-towards=black
